name: Build and Test

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: build-and-test-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:

  BuildAndTest:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3

    - name: "Set up Go"
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.4

    - name: "Build"
      run: make

    - name: "Test"
      run: |
        make test
